apiVersion: v1
kind: ConfigMap
metadata:
  name: imenu-config
data:
  DEBUG: "True"
---
apiVersion: v1
kind: Secret
metadata:
  name: postgres-credentials
type: Opaque
data:
  user: {{ .Values.externalPostgresql.postgresqlUsername | b64enc | quote}}
  password: {{ .Values.externalPostgresql.postgresqlPassword | b64enc | quote}}
  dbname: {{ .Values.externalPostgresql.postgresqlDatabase | b64enc | quote }}