apiVersion: apps/v1
kind: Deployment
metadata:
  name: {{ include "imenu-chart.fullname" . }}
  labels:
    {{- include "imenu-chart.labels" . | nindent 4 }}
spec:
  replicas: {{ .Values.replicaCount }}
  selector:
    matchLabels:
      {{- include "imenu-chart.selectorLabels" . | nindent 6 }}
  template:
    metadata:
      annotations:
        checksum/config: {{include (print $.Template.BasePath "/config.yaml") . | sha256sum }}
      labels:
        {{- include "imenu-chart.selectorLabels" . | nindent 8 }}
    spec:
      containers:
        - name: {{ .Chart.Name }}
          image: "{{ .Values.image }}"
          command: [ '/bin/bash', 'docker-entrypoint.sh' ]
          ports:
            - name: http
              containerPort: 80
              protocol: TCP
          env:
            - name: DB_NAME
              value: "imenu_db"
            - name: DB_USER
              valueFrom:
                secretKeyRef:
                  name: postgres-credentials
                  key: user
            - name: DB_PASSWORD
              valueFrom:
                secretKeyRef:
                  name: postgres-credentials
                  key: password
            - name: DB_HOST
              value: "postgres"
            - name: DB_PORT
              value: "5432"
            - name: DEBUG
              valueFrom:
                configMapKeyRef:
                  name: imenu-config
                  key: DEBUG