{{- if $.Values.serviceAccount.create -}}
apiVersion: v1
kind: ServiceAccount
metadata:
  name: {{ include "imenu-chart.serviceAccountName" $ }}
  labels:
    {{- include "imenu-chart.labels" . | nindent 4 }}
  {{- with $.Values.serviceAccount.annotations }}
  annotations:
    {{- toYaml $ | nindent 4 }}
  {{- end }}
{{- end }}
