apiVersion: apps/v1
kind: Deployment
metadata:
  name: imenu-deployment
spec:
  replicas: 2
  selector:
    matchLabels:
      app: imenu-py-app
  template:
    metadata:
      labels:
        app: imenu-py-app
    spec:
      containers:
        - name: imenu
          image: imenu:v1
          command: [ '/bin/bash', 'docker-entrypoint.sh' ]
          env:
            - name: DB_NAME
              value: "imenu_db"

            - name: DB_USER
              valueFrom:
                secretKeyRef:
                  name: postgres-credentials
                  key: user

            - name: DB_PASSWORD
              valueFrom:
                secretKeyRef:
                  name: postgres-credentials
                  key: password

            - name: DB_HOST
              value: "postgres"
            - name: DB_PORT
              value: "5432"
          ports:
            - name: web
              containerPort: 80

